<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="TestNGIWScripts.FailedRetryAnalyzerTestCase" tests="4" time="0.031" ignored="0" failures="1" timestamp="25 Apr 2020 05:06:29 GMT" skipped="3" hostname="LAPTOP-HH4641CU" errors="0">
  <testcase name="RetryTestCase" time="0.015" classname="TestNGIWScripts.FailedRetryAnalyzerTestCase">
    <skipped/>
  </testcase> <!-- RetryTestCase -->
  <testcase name="RetryTestCase" time="0.016" classname="TestNGIWScripts.FailedRetryAnalyzerTestCase">
    <failure type="junit.framework.ComparisonFailure" message="expected:&lt;[tru]e&gt; but was:&lt;[fals]e&gt;">
      <![CDATA[junit.framework.ComparisonFailure: expected:<[tru]e> but was:<[fals]e>
	at junit.framework.Assert.assertEquals(Assert.java:85)
	at junit.framework.Assert.assertEquals(Assert.java:91)
	at TestNGIWScripts.FailedRetryAnalyzerTestCase.RetryTestCase(FailedRetryAnalyzerTestCase.java:12)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:998)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1200)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- RetryTestCase -->
  <testcase name="RetryTestCase" time="0.000" classname="TestNGIWScripts.FailedRetryAnalyzerTestCase">
    <skipped/>
  </testcase> <!-- RetryTestCase -->
  <testcase name="RetryTestCase" time="0.000" classname="TestNGIWScripts.FailedRetryAnalyzerTestCase">
    <skipped/>
  </testcase> <!-- RetryTestCase -->
</testsuite> <!-- TestNGIWScripts.FailedRetryAnalyzerTestCase -->
